const sampleAppImages = [
  {
    'key': 'sample_avatar_1',
    'image': 'assets/images/avatar_1.png',
  },
  {
    'key': 'sample_avatar_2',
    'image': 'assets/images/avatar_2.png',
  },
  {
    'key': 'sample_avatar_3',
    'image': 'assets/images/avatar_3.png',
  },
  {
    'key': 'sample_avatar_4',
    'image': 'assets/images/avatar_4.png',
  },
  {
    'key': 'sample_avatar_5',
    'image': 'assets/images/avatar_5.png',
  },
  {
    'key': 'sample_avatar_6',
    'image': 'assets/images/avatar_6.png',
  },
  {
    'key': 'sample_avatar_7',
    'image': 'assets/images/avatar_7.png',
  },
  {
    'key': 'sample_avatar_8',
    'image': 'assets/images/avatar_8.png',
  },
  {
    'key': 'placeholder',
    'image': 'assets/images/placeholder.png',
  }
];

const List<Map<String, String>> shows = [
  {'key': '1', 'name': 'Movie 1'},
  {'key': '2', 'name': 'Movie 2'},
  {'key': '3', 'name': 'Movie 3'},
  {'key': '4', 'name': 'Movie 4'},
  {'key': '5', 'name': 'Movie 5'},
  {'key': '6', 'name': 'Movie 6'},
  {'key': '7', 'name': 'Movie 7'},
  {'key': '8', 'name': 'Movie 8'},
  {'key': '9', 'name': 'Movie 9'},
  {'key': '10', 'name': 'Movie 10'},
  {'key': '11', 'name': 'Web Series 1'},
  {'key': '12', 'name': 'Web Series 2'},
  {'key': '13', 'name': 'Web Series 3'},
  {'key': '14', 'name': 'Web Series 4'},
  {'key': '15', 'name': 'Web Series 5'},
  {'key': '16', 'name': 'Web Series 6'},
  {'key': '17', 'name': 'Web Series 7'},
  {'key': '18', 'name': 'Web Series 8'},
  {'key': '19', 'name': 'Web Series 9'},
  {'key': '20', 'name': 'Web Series 10'},
  {'key': '21', 'name': 'Drama TV Show 1'},
  {'key': '22', 'name': 'Drama TV Show 2'},
  {'key': '23', 'name': 'Drama TV Show 3'},
  {'key': '24', 'name': 'Drama TV Show 4'},
  {'key': '25', 'name': 'Drama TV Show 5'},
  {'key': '26', 'name': 'Drama TV Show 6'},
  {'key': '27', 'name': 'Drama TV Show 7'},
  {'key': '28', 'name': 'Drama TV Show 8'},
  {'key': '29', 'name': 'Drama TV Show 9'},
  {'key': '30', 'name': 'Drama TV Show 10'},
  {'key': '31', 'name': 'Reality Show 1'},
  {'key': '32', 'name': 'Reality Show 2'},
  {'key': '33', 'name': 'Reality Show 3'},
  {'key': '34', 'name': 'Reality Show 4'},
  {'key': '35', 'name': 'Reality Show 5'},
  {'key': '36', 'name': 'Reality Show 6'},
  {'key': '37', 'name': 'Reality Show 7'},
  {'key': '38', 'name': 'Reality Show 8'},
  {'key': '39', 'name': 'Reality Show 9'},
  {'key': '40', 'name': 'Reality Show 10'},
  {'key': '41', 'name': 'Movie 11'},
  {'key': '42', 'name': 'Movie 12'},
  {'key': '43', 'name': 'Movie 13'},
  {'key': '44', 'name': 'Movie 14'},
  {'key': '45', 'name': 'Movie 15'},
  {'key': '46', 'name': 'Movie 16'},
  {'key': '47', 'name': 'Movie 17'},
  {'key': '48', 'name': 'Movie 18'},
  {'key': '49', 'name': 'Movie 19'},
  {'key': '50', 'name': 'Movie 20'},
  {'key': '51', 'name': 'Web Series 11'},
  {'key': '52', 'name': 'Web Series 12'},
  {'key': '53', 'name': 'Web Series 13'},
  {'key': '54', 'name': 'Web Series 14'},
  {'key': '55', 'name': 'Web Series 15'},
  {'key': '56', 'name': 'Web Series 16'},
  {'key': '57', 'name': 'Web Series 17'},
  {'key': '58', 'name': 'Web Series 18'},
  {'key': '59', 'name': 'Web Series 19'},
  {'key': '60', 'name': 'Web Series 20'},
  {'key': '61', 'name': 'Drama TV Show 11'},
  {'key': '62', 'name': 'Drama TV Show 12'},
  {'key': '63', 'name': 'Drama TV Show 13'},
  {'key': '64', 'name': 'Drama TV Show 14'},
  {'key': '65', 'name': 'Drama TV Show 15'},
  {'key': '66', 'name': 'Drama TV Show 16'},
  {'key': '67', 'name': 'Drama TV Show 17'},
  {'key': '68', 'name': 'Drama TV Show 18'},
  {'key': '69', 'name': 'Drama TV Show 19'},
  {'key': '70', 'name': 'Drama TV Show 20'},
  {'key': '71', 'name': 'Reality Show 11'},
  {'key': '72', 'name': 'Reality Show 12'},
  {'key': '73', 'name': 'Reality Show 13'},
  {'key': '74', 'name': 'Reality Show 14'},
  {'key': '75', 'name': 'Reality Show 15'},
  {'key': '76', 'name': 'Reality Show 16'},
  {'key': '77', 'name': 'Reality Show 17'},
  {'key': '78', 'name': 'Reality Show 18'},
  {'key': '79', 'name': 'Reality Show 19'},
  {'key': '80', 'name': 'Reality Show 20'},
  {'key': '81', 'name': 'Movie 21'},
  {'key': '82', 'name': 'Movie 22'},
  {'key': '83', 'name': 'Movie 23'},
  {'key': '84', 'name': 'Movie 24'},
  {'key': '85', 'name': 'Movie 25'},
  {'key': '86', 'name': 'Movie 26'},
  {'key': '87', 'name': 'Movie 27'},
  {'key': '88', 'name': 'Movie 28'},
  {'key': '89', 'name': 'Movie 29'},
  {'key': '90', 'name': 'Movie 30'},
  {'key': '91', 'name': 'Web Series 21'},
  {'key': '92', 'name': 'Web Series 22'},
  {'key': '93', 'name': 'Web Series 23'},
  {'key': '94', 'name': 'Web Series 24'},
  {'key': '95', 'name': 'Web Series 25'},
  {'key': '96', 'name': 'Web Series 26'},
  {'key': '97', 'name': 'Web Series 27'},
  {'key': '98', 'name': 'Web Series 28'},
  {'key': '99', 'name': 'Web Series 29'},
  {'key': '100', 'name': 'Web Series 30'},
];
